---
- name: Create directory for DB data
  file:
    path:  '{{ item.path }}'
    owner: '{{ item.get("owner", "dockremap") }}'
    group: '{{ item.get("group", "dockremap") }}'
    mode:  '{{ item.get("mode",  "0750") }}'
    state: 'directory'
  with_items:
    - { path: '{{ openkm_service_path }}',       group: 'docker'                     }
    - { path: '{{ openkm_app_cont_vol }}',       group: 'docker'                     }
    - { path: '{{ openkm_app_cont_vol }}/docker',group: 'docker'                     }
    - { path: '{{ openkm_app_cont_vol }}/data',  owner: '{{ openkm_app_cont_uid }}'  }
    - { path: '{{ openkm_app_cont_vol }}/conf',  owner: '{{ openkm_app_cont_uid }}'  }
    - { path: '{{ openkm_app_cont_vol }}/logs',  owner: '{{ openkm_app_cont_uid }}'  }
    - { path: '{{ openkm_app_cont_vol }}/repo',  owner: '{{ openkm_app_cont_uid }}'  }
    - { path: '{{ openkm_db_cont_vol }}/data',   owner: '{{ openkm_db_cont_uid }}'   }
    - { path: '{{ openkm_db_cont_vol }}/backup', owner: '{{ openkm_db_cont_uid }}'   }
    - { path: '{{ openkm_xvfb_cont_vol }}',      group: '{{ openkm_xvfb_cont_uid }}', mode: '1777' }
    - { path: '{{ openkm_mail_cont_vol }}',      group: 'docker'                     }

- name: Template container env files
  register: openkm_cont_env
  template:
    src:   '{{ item }}'
    dest:  '{{ openkm_service_path }}/{{ item | basename }}'
    owner: 'dockremap'
    group: 'docker'
    mode:  '0640'
  with_fileglob:
    - 'templates/env/*'

- name: Template OpenKM config file
  register: openkm_config
  template:
    src:   'openkm.properties.j2'
    dest:  '{{ openkm_app_cont_vol }}/conf/openkm.properties'
    owner: '{{ openkm_app_cont_uid }}'
    group: 'docker'
    mode:  '0644'

- name: Template SMTP healcheck script
  template:
    src:   'scripts/smtp_healthcheck.sh.j2'
    dest:  '{{ openkm_mail_cont_vol }}/healthcheck.sh'
    owner: 'dockremap'
    group: 'docker'
    mode:  '0755'

- name: Create installation ID file
  when: openkm_installation_id is defined
  copy:
    content: '{{ openkm_installation_id }}'
    dest:  '{{ openkm_app_cont_vol }}/repo/.system.key'
    owner: '{{ openkm_app_cont_uid }}'
    group: '{{ openkm_app_cont_uid }}'
    mode:  '0640'
