---
- name: Create directory for DB data
  file:
    path:  '{{ item.path }}'
    owner: '{{ item.get("owner", "dockremap") }}'
    group: '{{ item.get("group", "dockremap") }}'
    state: 'directory'
    mode:  0750
  with_items:
    - { path: '{{ openkm_service_path }}',       group: 'docker'                    }
    - { path: '{{ openkm_app_cont_vol }}',       owner: '{{ openkm_app_host_uid }}' }
    - { path: '{{ openkm_app_cont_vol }}/data',  owner: '{{ openkm_app_host_uid }}' }
    - { path: '{{ openkm_db_cont_vol }}/data',   owner: '{{ openkm_db_host_uid }}'  }
    - { path: '{{ openkm_db_cont_vol }}/backup', owner: '{{ openkm_db_host_uid }}'  }

- name: Template container env files
  register: openkm_cont_env
  template:
    src:   '{{ item }}'
    dest:  '{{ openkm_service_path }}/{{ item | basename }}'
    owner: 'dockremap'
    group: 'docker'
    mode:  '0640'
  with_fileglob:
    - 'templates/env/*' 

- name: Template OpenKM config file
  register: openkm_config
  template:
    src:   'openkm.properties.j2'
    dest:  '{{ openkm_app_cont_vol }}/openkm.properties'
    owner: '{{ openkm_app_host_uid }}'
    group: 'docker'
    mode:  '0644'
