---
- name: Create Consul service definition
  include_role: name=infra-role-consul-service
  vars:
    consul_config_name: '{{ openkm_service_name }}'
    consul_services:
      - id:   '{{ openkm_service_name }}'
        name: '{{ openkm_service_name }}'
        tags: ['openkm', 'docs']
        port: '{{ openkm_app_cont_port }}'
        checks:
          - id: '{{ openkm_service_name }}-health'
            name: 'OpenKM Healthcheck'
            type: 'http'
            http: 'http://localhost:{{ openkm_app_cont_port }}/openkm/kcenter/'
